baseurl = "https://milestonebrewing.netlify.app/"
title = "Milestone Brewing"
author = "wazatoki"
canonifyurls = true
languagecode = "jp"
theme = "hugo-tanka"

enableEmoji = true
hasCJKLanguage = true

pygmentsstyle = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]
  sitename = "Milestone Brewing"
  sitesubname = "東加古川醸造所"
  homeimagecaption = "since 2018"
  faviconfile = "images/favicon.png"
  highlightjs = true
  highlightjslanguages = ["r", "python", "stan"]
  uselatex = true
  progressively = false
# commentsrepo = "user/repo"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[[menu.primary]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.primary]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.primary]]
    name = "on line store"
    url = "http://milestonebrewing.stores.jp"
    weight = 3
